rewardify_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_component.urls')),
    path('adminstrator/', include('admin_component.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_component/urls.py
from django.urls import path
from . import views as user_views


urlpatterns = [
    path('', user_views.login_view, name='login'),
    path('signup/', user_views.signup_view, name='signup'),
    path('home/', user_views.user_home, name='user_home'),
    path('installed_app/<int:app_id>/', user_views.installed_app_detail, name='installed_app_detail'),
    path('profile/', user_views.user_profile, name='user_profile'),
    path('points/', user_views.user_points, name='user_points'),
    path('leaderboard/', user_views.leaderboard, name='leaderboard'),
    path('tasks/', user_views.user_tasks, name='user_tasks'),
    path('tasks/<int:app_id>/', user_views.task_detail, name='task_detail'),
    path('tasks/<int:app_id>/upload/', user_views.upload_screenshot, name='upload_screenshot'),
    path('logout/', user_views.logout_view, name='logout'),
    path('dashboard/', user_views.user_dashboard, name='user_dashboard'),
]

user_component/models.py
from django.db import models
from django.contrib.auth.models import User
from admin_component.models import App


class Screenshot(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    app = models.ForeignKey(App, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='screenshots/')
    uploaded_at = models.DateTimeField(auto_now_add=True)
    

user_component/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from user_component.models import Screenshot


class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required= True, help_text='First Name')
    last_name = forms.CharField(max_length=30, required= True, help_text='Last Name')
    email = forms.EmailField(max_length=254, required= True, help_text='Email Address')

    class Meta:
        model = User
        fields =('username', 'first_name', 'last_name', 'email', 'password1', 'password2')


class ScreenshotUploadForm(forms.ModelForm):
    class Meta:
        model = Screenshot
        fields = ['image']

class ProfileUpdateForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(), required=False)
    confirm_password = forms.CharField(widget=forms.PasswordInput(), required=False)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

user_component/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Sum
from django.db import transaction
from .forms import CustomUserCreationForm, ScreenshotUploadForm, ProfileUpdateForm
from admin_component.models import App, AppUsers
from user_component.models import Screenshot
import json



def format_data(apps):
    app_data = []
    for app in apps:
        name= app.app_name
        link= app.app_link
        category =app.app_category
        sub_category =app.sub_category
        image= app.app_image
        points = app.points
        id=app.id
        app_data.append({
            'id':id,
            'app': app,
            'name':name,
            'link': link,
            'category' :category,
            'subcategory' : sub_category,
            'points' : points,
            'image' : image, 
            'id' :id
        })
    return app_data
def signup_view(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        print(f"form: {form.is_valid()}")
        if form.is_valid():
            user=form.save()
            username = form.cleaned_data.get('username')
            password =  form.cleaned_data.get('password1')
            user = authenticate(username =username, password= password)
            print(f"Authenticated user:{user}")
            if user is not None:
                login(request,user)
                return redirect('user_home')
        else:
            print(form.errors)
            return render(request, 'signup.html', {'form': form})
    else:
        form =UserCreationForm()
    return render(request, 'signup.html', {'form':form})   

def login_view(request):
    if request.method == "POST":
        form= AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request,user)
            if user.is_staff:
                return redirect('admin_home')
            else:
                return redirect('user_home')
        else:
            print(form.errors,"user_login")
            return render(request, 'login.html', {'form': form})
    else:
        form =AuthenticationForm()
    return render(request, 'login.html', {'form':form})   


@login_required
def user_home(request):
    installed_apps = App.objects.filter(appusers__user=request.user)
    return render(request, 'user_home.html', {'apps': installed_apps})

@login_required
def user_profile(request):
    user = request.user
    if request.method == 'POST':
        form = ProfileUpdateForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            messages.success(request, 'Your profile has been updated successfully!')
            return redirect('user_profile')
    else:
        form = ProfileUpdateForm(instance=user)
    return render(request, 'user_profile.html', {'form': form})

@login_required
def user_points(request):
    user = request.user
    total_points = AppUsers.objects.filter(user=user).aggregate(Sum('app__points'))['app__points__sum'] or 0

    category_points = (
        AppUsers.objects.filter(user=user)
        .values('app__app_category__name')
        .annotate(total=Sum('app__points'))
        .order_by('app__app_category__name')
    )

    sub_category_points = (
        AppUsers.objects.filter(user=user)
        .values('app__sub_category__name')
        .annotate(total=Sum('app__points'))
        .order_by('app__sub_category__name')
    )

    context = {
        'total_points': total_points,
        'category_points': json.dumps(list(category_points), cls=DjangoJSONEncoder),
        'sub_category_points': json.dumps(list(sub_category_points), cls=DjangoJSONEncoder),
    }
    return render(request, 'user_points.html', context)

@login_required
def leaderboard(request):
    leaderboard_data = (
        AppUsers.objects.values('user__username')
        .annotate(total_points=Sum('app__points'))
        .order_by('-total_points')
    )

    context = {
        'leaderboard_data': leaderboard_data,
    }
    return render(request, 'leaderboard.html', context)

@login_required
def user_tasks(request):
    # Apps that the user has not installed yet
    installed_apps_ids = AppUsers.objects.filter(user=request.user).values_list('app_id', flat=True)
    tasks_apps = App.objects.exclude(id__in=installed_apps_ids)
    print(tasks_apps)
    data=format_data(tasks_apps)
    return render(request, 'user_tasks.html', {'apps':data })

@login_required
def task_detail(request, app_id):
    app = get_object_or_404(App, id=app_id)
    return render(request, 'task_detail.html', {'app': app})

@login_required
def upload_screenshot(request, app_id):
    app = get_object_or_404(App, id=app_id)
    if request.method == 'POST':
        form = ScreenshotUploadForm(request.POST, request.FILES)

        if form.is_valid():
            with transaction.atomic():
                screenshot = form.save(commit=False)
                screenshot.user = request.user
                screenshot.app = app
                screenshot.save()
                AppUsers.objects.create(user=request.user, app=app)
            messages.success(request, 'Screenshot uploaded successfully.')
            return redirect('user_tasks')
        else:
            messages.error(request, 'Failed to upload screenshot.')
    return redirect('task_detail', app_id=app_id)

@login_required
def installed_app_detail(request, app_id):
    app = get_object_or_404(App, id=app_id)
    screenshot = get_object_or_404(Screenshot, app=app, user=request.user)
    return render(request, 'installed_app_detail.html', {'app': app, 'screenshot': screenshot})


def logout_view(request):
    logout(request)
    return redirect('login')

@login_required
def user_dashboard(request):
    # Get the current logged-in user
    user = request.user

    # Assuming you have a field named 'username' in your User model
    username = user.username

    # Get total points for the user (assuming a 'user' foreign key in the Point model)
    # total_points = Point.objects.filter(user=user).aggregate(total_points=Sum('points'))['total_points'] or 0

    # Get points breakdown by platform (assuming a 'platform' field in the Point model)
    # points_breakdown = Point.objects.filter(user=user).values('platform').annotate(total_points=Sum('points'))

    context = {
        'username': username,
        'total_points': 10,
        # 'points_breakdown': points_breakdown,
    }
    return render(request, 'user_dashboard.html', context)

user_component/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_home.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/task_detail.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    {% block extra_head %}{% endblock %}
</head>
<body>
    <div class="header">
        <h1>Hello, {{ user.username }}</h1>
    </div>
    <div class="container">
        <div class="sidebar">
            <a href="{% url 'user_home' %}" class="home-button"><i class="fas fa-home"></i> Home</a>
            <a href="{% url 'user_profile' %}" class="profile-button"><i class="fas fa-user"></i> Profile</a>
            <a href="{% url 'user_points' %}" class="points-button"><i class="fas fa-star"></i> Points</a>
            <a href="{% url 'user_tasks' %}" class="tasks-button"><i class="fas fa-tasks"></i> Tasks</a>
            <a href="{% url 'logout' %}" class="logout-button"><i class="fas fa-sign-out-alt"></i> Logout</a>
        </div>
        <div class="content">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

user_component/templates/installed_app_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}{{ app.name }}{% endblock %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/installed_app_detail.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="content">
        <div class="app-item">
            <img src="{{ app.app_image.url }}" alt="{{ app.app_name }}" class="app-icon">
            <div class="app-details">
                <h3>{{ app.app_name }}</h3>
                <a href="{{ app.app_link }}" target="_blank">{{ app.app_link }}</a>
            </div>
            <div class="app-points">
                <p>{{ app.points }} POINTS</p>
            </div>
        </div>
        <div class="screenshot-section">
            {% if screenshot %}
            <img src="{{ screenshot.image.url }}" alt="Screenshot" class="screenshot-image">
            {% else %}
            <p>No screenshot available.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

user_component/templates/leaderboard.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Leaderboard{% endblock %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/leaderboard.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <table>
        <thead>
            <tr>
                <th>Rank</th>
                <th>Username</th>
                <th>Total Points</th>
            </tr>
        </thead>
        <tbody>
            {% for user in leaderboard_data %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ user.user__username }}</td>
                    <td>{{ user.total_points }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

user_component/templates/login.html
<!-- Login Page-->

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="UTF-8">
  <title>Login</title>
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body class="align">

  <div class="grid align__item">

    <div class="register">

      <svg xmlns="http://www.w3.org/2000/svg" class="site__logo" width="56" height="84" viewBox="77.7 214.9 274.7 412"><defs><linearGradient id="a" x1="0%" y1="0%" y2="0%"><stop offset="0%" stop-color="#8ceabb"/><stop offset="100%" stop-color="#378f7b"/></linearGradient></defs><path fill="url(#a)" d="M215 214.9c-83.6 123.5-137.3 200.8-137.3 275.9 0 75.2 61.4 136.1 137.3 136.1s137.3-60.9 137.3-136.1c0-75.1-53.7-152.4-137.3-275.9z"/></svg>

      <h2>Login</h2>

      <form action="{% url 'login' %}" method="post" class="form">
        {% csrf_token %}
        {% if form.errors %}
          <div class="form__field">
            <p style="color: red; font-weight: bold;" class="error">Invalid username or password. Please try again.</p>
          </div>
        {% endif %}
        <div class="form__field">
          <input type="text" name="username" placeholder="Enter your username">
          {{form.username.errors}}
        </div>

        <div class="form__field">
          <input type="password" name="password" placeholder="Enter your password">
        </div>

        <div class="form__field">
          <input type="submit" value="Login">
        </div>

      </form>
      {% if errorlist %}
        <p style="color: red; font-weight: bold;">{{ errorlist }}</p> <!-- Display error message if it exists -->
      {% endif %}
      <p>Don't have an accout? <a href="{% url 'signup' %}">Sign Up</a></p>
      
    </div>

  </div>

</body>
</html>

user_component/templates/signup.html
<!-- Sign up Page-->

{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="UTF-8">
  <title>Sign Up</title>
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">

</head>
<body class="align">

  <div class="grid align__item">

    <div class="register">

      <svg xmlns="http://www.w3.org/2000/svg" class="site__logo" width="56" height="84" viewBox="77.7 214.9 274.7 412"><defs><linearGradient id="a" x1="0%" y1="0%" y2="0%"><stop offset="0%" stop-color="#8ceabb"/><stop offset="100%" stop-color="#378f7b"/></linearGradient></defs><path fill="url(#a)" d="M215 214.9c-83.6 123.5-137.3 200.8-137.3 275.9 0 75.2 61.4 136.1 137.3 136.1s137.3-60.9 137.3-136.1c0-75.1-53.7-152.4-137.3-275.9z"/></svg>

      <h2>Rewardify</h2>

      <form action="{% url 'signup' %}" method="post" class="form">
        {% csrf_token %}
        <div class="form__field">
          <input type="text" name="username" placeholder="Enter your username">
          {{form.username.errors}}
        </div>

        <div class="form__field">
          <input type="text" name="first_name" placeholder="Enter your First Name">
          {{form.firstname.errors}}
        </div>

        <div class="form__field">
          <input type="text" name="last_name" placeholder="Enter your Last Name">
          {{form.lastname.errors}}
        </div>

        <div class="form__field">
          <input type="email" name="email" placeholder="Enter your email">
          {{form.email.errors}}
        </div>

        <div class="form__field">
          <input type="password" name= "password1" placeholder="••••••••••••">
          {{form.password.errors}}
        </div>

        <div class="form__field">
          <input type="password" name="password2" placeholder="Confirm your password">
          {{ form.password2.errors }}
        </div>

        <div class="form__field">
          <input type="submit" value="Sign Up">
        </div>

      </form>
      {% if error_message %}
      <p style="color: red; font-weight: bold;">{{ error_message }}</p> <!-- Display error message if it exists -->
      {% endif %}
      <p>Already have an accout? <a href="{% url 'login' %}">Log in</a></p>

    </div>

  </div>

</body>
</html>

user_component/templates/task_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ app.name }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="content">
            <div class="app-item">
                <img src="{{ app.app_image.url }}" alt="{{ app.app_name }}" class="app-icon">
                <div class="app-details">
                    <h3>{{ app.app_name }}</h3>
                    <a href="{{ app.app_link }}" target="_blank">{{ app.app_link }}</a>
                </div>
                <div class="app-points">
                    <p>{{ app.points }} POINTS</p>
                </div>
            </div>
            <div class="upload-section">
                <img src="{% static 'images/upload_placeholder.jpg' %}" alt="Upload" class="upload-icon">
                <p>Upload Screenshots to complete the Task</p>
                <form action="{% url 'upload_screenshot' app.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <input type="file" name="image">
                    <button type="submit">Upload</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

user_component/templates/user_dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Dashboard</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_dashboard.css' %}">
<body>
    <header class="header">
        <h1>Hello {{username}}</h1>
        <a href="#">Home</a>
        <a href="#">Profile</a>
    </header>
    <div class="points">
        <h2>Facebook</h2>
        <p>100 POINTS</p>
        <a href="#" class="detail">View in Detail ></a>
    </div>
    <div class="points">
        <h2>Task</h2>
        <p>-</p>  <a href="#" class="detail">View in Detail ></a>
    </div>
    <div class="points">
        <h2>Snapchat</h2>
        <p>75 POINTS</p>
        <a href="#" class="detail">View in Detail ></a>
    </div>
    <div class="points">
        <h2>LinkedIn</h2>
        <p>150 POINTS</p>
        <a href="#" class="detail">View in Detail ></a>
    </div>
</body>
</html>

user_component/templates/user_home.html
{% extends 'base.html' %}

{% block title %}Tasks{% endblock %}


{% block content %}
    <div class="container">
        <div class="content">
            <h2>App List</h2>
            <ul class="app-list">
                {% for app in apps %}
                <li class="app-item">
                    <img src="{{ app.app_image.url }}" alt="{{ app.app_name }}" class="app-icon">
                    <div class="app-details">
                        <h3>{{ app.app_name }}</h3>
                        <p>{{ app.description }}</p>
                        <a href="{% url 'installed_app_detail' app.id %}">View in detail</a>
                    </div>
                    <div class="app-points">
                        <p>{{ app.points }} POINTS</p>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

user_component/templates/user_points.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Points Dashboard{% endblock %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/user_points.css' %}">
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
{% endblock %}

{% block content %}
<div class="container">
    <div class="top-section">
        <div class="total-points">Total Points: {{ total_points }}</div>
        <a href="{% url 'leaderboard' %}" class="leaderboard-button">Leaderboard</a>
    </div>
    <div class="charts-container">
        <div class="chart">
            <h3>Points by Category</h3>
            <canvas id="category-points-chart" width="400" height="400"></canvas>
        </div>
        <div class="chart">
            <h3>Points by SubCategory</h3>
            <canvas id="subcategory-points-chart" width="400" height="400"></canvas>
        </div>
    </div>
    <script id="categoryLabels" type="application/json">{{ category_points|safe }}</script>
    <script id="categoryData" type="application/json">{{ category_points|safe }}</script>
    <script id="subCategoryLabels" type="application/json">{{ sub_category_points|safe }}</script>
    <script id="subCategoryData" type="application/json">{{ sub_category_points|safe }}</script>
</div>
<script src="{% static 'js/points_dashboard.js' %}"></script>
{% endblock %}

user_component/templates/user_profile.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Profile{% endblock %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" href="{% static 'css/user_profile.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="content">
        <form method="post">
            {% csrf_token %}
            <div class="profile-pic">
                <img src="{% static 'images/default_profile.png' %}" alt="Profile Picture">
                <p>{{ user.username }}</p>
            </div>
            <div class="form-group">
                <label for="id_first_name">First Name:</label>
                {{ form.first_name }}
            </div>
            <div class="form-group">
                <label for="id_last_name">Last Name:</label>
                {{ form.last_name }}
            </div>
            <div class="form-group">
                <label for="id_email">Email:</label>
                {{ form.email }}
            </div>
        </form>
        {% if messages %}
            {% for message in messages %}
                <div class="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
    </div>
</div>
{% endblock %}

user_component/templates/user_tasks.html
{% extends 'base.html' %}

{% block title %}Tasks{% endblock %}

{% block content %}
    <div class="container">
        <div class="content">
            <ul class="app-list">
                {% for app in apps %}
                <li class="app-item">
                    <img src="{{ app.image.url }}" alt="{{ app.name }}" class="app-icon">
                    <div class="app-details">
                        <h3>{{ app.name }}</h3>
                        <a href="{% url 'task_detail' app.id %}">View in Detail ></a>
                    </div>
                    <div class="app-points">
                        <a href="{{ app.link }}" target="_blank">{{ app.points }} POINTS</a>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}